version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./../public:/var/www/html
      - ./../backend:/var/www/html/backend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ./../public:/var/www/html
      - ./../backend:/var/www/html/backend
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=yabiso_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=23525689
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./../init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge