version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./../public:/var/www/html
      - ./../backend:/var/www/html/backend
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
      - postgres
    networks:
      - app-network

  php:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ./../public:/var/www/html
      - ./../backend:/var/www/html/backend
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=yabiso_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=23525689
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./../init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@yabiso.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge